[projects]
name = "FusionSynth"
description = "A voice synthesizer that custom everything."
version = "0.0.1"
license = "GPL-2.0"
internal_version = true
authors = ["RainyXeon", "DeepLunaria Foundation"]
codename = "Scilla"